# Generated by Django 3.1.1 on 2020-09-22 19:31

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.FileField(default=1, help_text='Maximum file size allowed is 2Mb', unique=True, upload_to='male/passport', validators=[app.models.validate_image]),
            preserve_default=False,
        ),
    ]
