# Generated by Django 3.1.1 on 2020-09-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200922_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blood_genotype',
            field=models.CharField(choices=[('AA', 'AA'), ('AS', 'AS'), ('SS', 'SS')], default=1, max_length=10, verbose_name='Blood Genotype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='blood_group',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], default=1, max_length=10, verbose_name='Blood Group'),
            preserve_default=False,
        ),
    ]
