# Generated by Django 3.1.1 on 2020-09-22 20:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_auto_20200922_2057'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Eductaion',
            new_name='Education',
        ),
    ]
