# Generated by Django 3.1.1 on 2020-09-22 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200922_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beards', models.BooleanField(default=True, verbose_name='Do You Keep Beards')),
                ('religious', models.CharField(choices=[('Muslim Since Birth', 'Muslim Since Birth'), ('Revert Muslim', 'Revert Muslim')], max_length=250, verbose_name='Religion History')),
                ('sect', models.CharField(choices=[('Al-Sunnah', 'Al-Sunnah'), ('Salafi', 'Salafi')], max_length=150, verbose_name='Which Sect Do you Belong to')),
                ('availablity', models.CharField(choices=[('Currently available for Nikkah', 'Currently available for Nikkah'), ('Currently not available for Nikkah', 'Currently not available for Nikkah')], max_length=500, verbose_name='Availability Status')),
            ],
            options={
                'verbose_name': 'AboutMe',
                'verbose_name_plural': 'AboutMes',
            },
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='availablity',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='beards',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='religious',
        ),
        migrations.AddField(
            model_name='aboutme',
            name='about_partner',
            field=models.TextField(default=1, verbose_name='About My Partner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutme',
            name='smoke',
            field=models.BooleanField(default=True, verbose_name='Do You Smoke'),
        ),
        migrations.AddField(
            model_name='education',
            name='income',
            field=models.PositiveIntegerField(default=1, verbose_name='Yearly Income'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='about_me',
            field=models.TextField(verbose_name='About Me'),
        ),
    ]
