# Generated by Django 3.1.1 on 2020-09-22 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200922_2139'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Religion',
        ),
    ]
