# Generated by Django 3.1.1 on 2020-09-22 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_religion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Religion',
        ),
    ]
