# Generated by Django 3.1.1 on 2020-09-22 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0010_delete_religion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beards', models.BooleanField(default=True, verbose_name='Do You Keep Beards')),
                ('religious', models.CharField(choices=[('Muslim Since Birth', 'Muslim Since Birth'), ('Revert Muslim', 'Revert Muslim')], max_length=250, verbose_name='Religion History')),
                ('sect', models.CharField(choices=[('Al-Sunnah', 'Al-Sunnah'), ('Salafi', 'Salafi')], max_length=150, verbose_name='Which Sect Do you Belong to')),
                ('availablity', models.CharField(choices=[('Currently available for Nikkah', 'Currently available for Nikkah'), ('Currently not available for Nikkah', 'Currently not available for Nikkah')], max_length=500, verbose_name='Availability Status')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='religion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Religion',
                'verbose_name_plural': 'Religion',
            },
        ),
    ]
