# Generated by Django 3.1.1 on 2020-09-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_religion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='religion',
            options={'verbose_name': 'Religion', 'verbose_name_plural': 'Religions'},
        ),
        migrations.AddField(
            model_name='profile',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Availability'),
        ),
    ]
