# Generated by Django 3.1.1 on 2020-09-23 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_takenquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='takenquestion',
            name='date',
        ),
    ]
