# Generated by Django 3.1.1 on 2020-09-24 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0015_remove_takenquestion_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutme',
            name='smoke',
        ),
        migrations.RemoveField(
            model_name='religion',
            name='availablity',
        ),
        migrations.AddField(
            model_name='aboutme',
            name='availablity',
            field=models.CharField(choices=[('Currently available for Nikkah', 'Currently available for Nikkah'), ('Currently not available for Nikkah', 'Currently not available for Nikkah')], default=1, max_length=500, verbose_name='Availability Status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutme',
            name='favorite',
            field=models.CharField(default=1, max_length=50, verbose_name='What are your favorite things about yourself?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutme',
            name='inspire',
            field=models.CharField(default=1, max_length=150, verbose_name='What inspires you must'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutme',
            name='vision',
            field=models.CharField(default=1, max_length=150, verbose_name='My Vision'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='religion',
            name='hijab',
            field=models.CharField(choices=[("I don't use Hijab", 'Al-Sunnah'), ('Scarf', 'Scarf'), ('Small-Hijab', 'Small-Hijab'), ('Mid-Hijab', 'Mid-Hijab'), ('Big-Hijab', 'Big-Hijab'), ('Khimar', 'Khimar'), ('Niqqab', 'Niqqab')], default=1, max_length=50, verbose_name='Your Hijab'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('Citizen', 'Citizen'), ('Visitation', 'Visitation'), ('Student', 'Student')], max_length=150, verbose_name='Citizen Status'),
        ),
        migrations.AlterField(
            model_name='education',
            name='education',
            field=models.CharField(choices=[('PhD', 'PhD'), ('MSc.', 'MSc'), ('BSc.', 'BSc'), ('HND', 'HND'), ('OND', 'OND'), ('Undergraduate', 'Undergraduate'), ('Secondary School Leaving', 'Secondary School Leaving'), ('Primary School', 'Primary School'), ('non Aplicable', 'Non Applicable')], max_length=250, verbose_name='Education'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='body_complex',
            field=models.CharField(choices=[('Light', 'Light'), ('Dark', 'Dark')], max_length=50, verbose_name='Complexion'),
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('childhood', models.CharField(max_length=150, verbose_name=' What was your childhood ambition?')),
                ('sight', models.CharField(max_length=150, verbose_name='Do you believe in love at first sight?')),
                ('love', models.CharField(max_length=150, verbose_name='Have you ever been in love?')),
                ('display', models.CharField(max_length=150, verbose_name='How do you display love')),
                ('phobia', models.CharField(max_length=150, verbose_name='What are your phobias in relationships?')),
                ('verted', models.CharField(choices=[('Introvert', 'Introverted'), ('Extrovert', 'Extrovert')], max_length=50, verbose_name='Are you introverted or extroverted?')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='character', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Character',
                'verbose_name_plural': 'Characters',
            },
        ),
    ]
