# Generated by Django 3.1.1 on 2020-09-24 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20200924_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='verted',
            field=models.CharField(choices=[('Introvert', 'Introvert'), ('Extrovert', 'Extrovert')], max_length=50, verbose_name='Are you introverted or extroverted?'),
        ),
    ]
