# Generated by Django 3.1.1 on 2020-09-25 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0017_auto_20200924_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(verbose_name='Interest Note')),
                ('status', models.CharField(choices=[('A', 'INTREST'), ('L', 'LET US TALK'), ('S', 'LET US SEE'), {'F', 'FINAL STAGE'}], default='A', max_length=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('intereser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interester', to=settings.AUTH_USER_MODEL)),
                ('interestin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interestin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'InterestData',
                'verbose_name_plural': 'InterestDatas',
            },
        ),
    ]
