# Generated by Django 3.1.1 on 2020-09-25 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20200925_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestdata',
            name='status',
            field=models.CharField(choices=[('I', 'INTEREST'), ('L', 'LET US TALK'), ('S', 'LET US SEE'), {'F', 'FINAL STAGE'}], default='A', max_length=13),
        ),
    ]
