# Generated by Django 3.1.1 on 2020-09-26 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20200925_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestdata',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
