# Generated by Django 3.1.1 on 2020-09-26 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_interestdata_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestdata',
            name='acceptance',
            field=models.TextField(default=1, verbose_name='Acceptance Note'),
            preserve_default=False,
        ),
    ]
