# Generated by Django 3.1.1 on 2020-09-26 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_interestdata_acceptance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestdata',
            name='acceptance',
            field=models.TextField(blank=True, null=True, verbose_name='Acceptance Note'),
        ),
        migrations.AlterField(
            model_name='interestdata',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Interest Note'),
        ),
    ]
