# Generated by Django 3.1.1 on 2020-09-26 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20200926_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestdata',
            name='acceptance',
            field=models.TextField(blank=True, null=True, verbose_name='Proceed Note'),
        ),
        migrations.AlterField(
            model_name='interestdata',
            name='status',
            field=models.CharField(choices=[('I', 'INTEREST'), ('L', 'LET US TALK'), ('S', 'LET US SEE'), {'F', 'FINAL STAGE'}, {'R', 'REJECT OFFER'}], default='A', max_length=13),
        ),
    ]
