# Generated by Django 3.1.1 on 2020-09-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20200926_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestdata',
            name='status',
            field=models.CharField(choices=[('I', 'INTEREST'), ('L', 'LET US TALK'), ('S', 'LET US SEE'), {'FINAL STAGE', 'F'}, {'R', 'REJECT OFFER'}], default='I', max_length=13),
        ),
    ]
