# Generated by Django 3.2.4 on 2021-06-26 06:48

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20210625_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(help_text='Maximum file size allowed is 2Mb', unique=True, upload_to='passport', validators=[app.models.validate_image], verbose_name='Passport Photography'),
        ),
    ]
