# Generated by Django 3.2.4 on 2021-06-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='religion',
            name='beards',
            field=models.BooleanField(choices=[('I am Female', 'I am female'), ('I keep beards', 'I keep beards'), ('I dont keep it', 'I dont keep it'), ('I dont Have beards', 'I Dont have Beards'), ('Little', 'Little')], verbose_name='Do You Keep Beards'),
        ),
        migrations.AlterField(
            model_name='religion',
            name='hijab',
            field=models.CharField(choices=[('I am Male', 'I am Male'), ("I don't use Hijab", 'I dont use Hijab'), ('Scarf', 'Scarf'), ('Small-Hijab', 'Small-Hijab'), ('Mid-Hijab', 'Mid-Hijab'), ('Big-Hijab', 'Big-Hijab'), ('Khimar', 'Khimar'), ('Niqqab', 'Niqqab')], max_length=50, verbose_name='Your Hijab'),
        ),
    ]
