# Generated by Django 3.2.4 on 2021-06-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_religion_imam_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='religion',
            name='sect',
            field=models.CharField(choices=[('Al-Sunnah', 'Al-Sunnah'), ('Salafi', 'Salafi'), ('Sufi', 'Sufi')], max_length=150, verbose_name='Which Sect Do you Belong to'),
        ),
    ]
