# Generated by Django 3.2.4 on 2021-06-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_religion_sect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='religion',
            name='hijab',
            field=models.CharField(choices=[('I am Male', 'I am Male'), ("I don't use Hijab", 'I dont use Hijab'), ('Scarf', 'Scarf'), ('Small-Hijab', 'Small-Hijab'), ('Mid-Hijab', 'Mid-Hijab'), ('Big-Hijab', 'Big-Hijab'), ('Khimar', 'Khimar'), ('Niqqab', 'Niqqab')], max_length=150, verbose_name='Your Hijab'),
        ),
    ]
