# Generated by Django 3.2.4 on 2021-06-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_alter_religion_hijab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='religion',
            name='beards',
            field=models.CharField(choices=[('I am Female', 'I am female'), ('I keep beards', 'I keep beards'), ('I dont keep it', 'I dont keep it'), ('I dont Have beards', 'I Dont have Beards'), ('Little', 'Little')], max_length=150, verbose_name='Do You Keep Beards'),
        ),
    ]
