# Generated by Django 3.2.4 on 2021-06-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_religion_beards'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='sibling',
            field=models.BooleanField(default=True, verbose_name='Do Your Hvae Siblings'),
        ),
        migrations.AddField(
            model_name='family',
            name='well',
            field=models.CharField(choices=[('First Class', 'First Class'), ('Middle Class', 'Middle Class'), ('Impoverished', 'Impoverished')], default=1, max_length=150, verbose_name='Were you well off'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='family',
            name='father_job',
            field=models.CharField(max_length=150, verbose_name='What did your Father Do for Living'),
        ),
        migrations.AlterField(
            model_name='family',
            name='mother_job',
            field=models.CharField(max_length=150, verbose_name='What did your Mother Do for Living'),
        ),
    ]
