# Generated by Django 3.2.4 on 2021-06-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20210627_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='education_description',
        ),
        migrations.AlterField(
            model_name='education',
            name='education',
            field=models.CharField(choices=[('PhD', 'PhD'), ('MSc.', 'MSc'), ('BSc.', 'BSc'), ('HND', 'HND'), ('OND', 'OND'), ('Undergraduate', 'Undergraduate'), ('Secondary School Leaving', 'Secondary School Leaving'), ('Primary School', 'Primary School'), ('non Aplicable', 'Non Applicable')], max_length=250, verbose_name='Highest Level Education'),
        ),
        migrations.AlterField(
            model_name='family',
            name='sibling',
            field=models.BooleanField(default=True, verbose_name='Do Your Have Siblings'),
        ),
    ]
