# Generated by Django 3.2.4 on 2021-06-29 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20210627_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='well',
            field=models.CharField(choices=[('First Class', 'First Class'), ('Middle Class', 'Middle Class'), ('Impoverished', 'Impoverished')], max_length=150, verbose_name='Were your Parents well off'),
        ),
    ]
