# Generated by Django 3.1.1 on 2020-09-20 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=1, max_length=50, verbose_name='Phine Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='term',
            field=models.ManyToManyField(related_name='term', to='user.Term'),
        ),
        migrations.AddField(
            model_name='user',
            name='who',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='who', to='user.who'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='IntroQuestion',
        ),
    ]
