# Generated by Django 3.2.4 on 2021-06-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_plan_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
