# Generated by Django 3.2.4 on 2021-06-29 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_subscription_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='is_active',
            new_name='diable',
        ),
    ]
