# Generated by Django 3.2.4 on 2021-06-29 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_rename_is_active_subscription_diable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='diable',
            new_name='disable',
        ),
    ]
